"undefined"===typeof LimelightPlayerUtil&&("undefined"===typeof JSON&&(this.JSON={},function(){function t(c){return 10>c?"0"+c:c}function B(c){C.lastIndex=0;return C.test(c)?'"'+c.replace(C,function(c){var e=J[c];return"string"===typeof e?e:"\\u"+("0000"+c.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+c+'"'}function y(c,u){var e,j,b,p,n=l,m,h=u[c];h&&("object"===typeof h&&"function"===typeof h.toJSON)&&(h=h.toJSON(c));"function"===typeof v&&(h=v.call(u,c,h));switch(typeof h){case "string":return B(h);
case "number":return isFinite(h)?String(h):"null";case "boolean":case "null":return String(h);case "object":if(!h)return"null";l+=z;m=[];if("[object Array]"===Object.prototype.toString.apply(h)){p=h.length;for(e=0;e<p;e+=1)m[e]=y(e,h)||"null";b=0===m.length?"[]":l?"[\n"+l+m.join(",\n"+l)+"\n"+n+"]":"["+m.join(",")+"]";l=n;return b}if(v&&"object"===typeof v){p=v.length;for(e=0;e<p;e+=1)if(j=v[e],"string"===typeof j&&(b=y(j,h)))m.push(B(j)+(l?": ":":")+b)}else for(j in h)if(Object.hasOwnProperty.call(h,
j)&&(b=y(j,h)))m.push(B(j)+(l?": ":":")+b);b=0===m.length?"{}":l?"{\n"+l+m.join(",\n"+l)+"\n"+n+"}":"{"+m.join(",")+"}";l=n;return b}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+t(this.getUTCMonth()+1)+"-"+t(this.getUTCDate())+"T"+t(this.getUTCHours())+":"+t(this.getUTCMinutes())+":"+t(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});
var D=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,C=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,l,z,J={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},v;"function"!==typeof JSON.stringify&&(JSON.stringify=function(c,u,e){var j;z=l="";if("number"===typeof e)for(j=0;j<e;j+=1)z+=" ";else"string"===typeof e&&(z=e);if((v=u)&&"function"!==
typeof u&&("object"!==typeof u||"number"!==typeof u.length))throw Error("JSON.stringify");return y("",{"":c})});"function"!==typeof JSON.parse&&(JSON.parse=function(c,l){function e(b,j){var c,m,h=b[j];if(h&&"object"===typeof h)for(c in h)Object.hasOwnProperty.call(h,c)&&(m=e(h,c),void 0!==m?h[c]=m:delete h[c]);return l.call(b,j,h)}var j;c=String(c);D.lastIndex=0;D.test(c)&&(c=c.replace(D,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(c.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return j=eval("("+c+")"),"function"===typeof l?e({"":j},""):j;throw new SyntaxError("JSON.parse");})}()),LimelightPlayerUtil=function(){function t(a){a=a||{};a.wmode=a.wmode||"window";a.id=a.id||"limelight_player_"+Math.floor(1E9*Math.random());a.resources=a.resources||{};a.resources.playlistService=a.resources.playlistService||l;a.resources.metricsCollectionService=a.resources.metricsCollectionService||
z;a.resources.cuePointService=a.resources.cuePointService||J;a.resources.htmlPlayerLocation=a.resources.htmlPlayerLocation||j.loadingProtocol+v;a.resources.playerIframeLocation=a.resources.playerIframeLocation||j.loadingProtocol+c;return a}function B(a,d,k,r,g,f,w,b,e){var c=x.create(d.metricsCollectionService,r,e);switch(e){case "iframe":return M(d,w,g,f,r,c,a);case "html":var h=null!==k?k:r;N(d,function(a){var k={service:{}};d.playlistService&&(k.service.playlistService=d.playlistService);d.metricsCollectionService&&
(k.service.metricsCollectionService=d.metricsCollectionService);d.cuePointService&&(k.service.cuePointService=d.cuePointService);return DelvePlayer=a=a.createPlayer(w,g,f,h,k)});return;case "video":D(d,r,j.htmlCodec,c,function(d,k){c.postStartSessionEvent();var r=k.mediaList[0],b=document.createElement("VIDEO");b.src=encodeURI(r.mobileUrls[0].mobileUrl);b.width=g;b.height=f;b.poster=encodeURI(r.previewImageUrl);b.controls=!0;b.addEventListener("click",b.play);b.addEventListener("play",function(){c.postPlayStateEvent(x.PLAY,
Math.round(1E3*b.currentTime));c.startHeartbeat({quality:d,getPosition:function(){return Math.round(1E3*b.currentTime)},isPlaying:function(){return!b.paused}})});b.addEventListener("pause",function(){b.ended||c.postPlayStateEvent(x.PAUSE,Math.round(1E3*b.currentTime));c.stopHeartbeat()});b.addEventListener("ended",function(){c.postEvent(x.MEDIA_COMPLETE);c.stopHeartbeat()});var w=0;b.addEventListener("timeupdate",function(){var a=b.currentTime;if(b.seeking&&a!==w){var d=Math.round(1E3*w),k=Math.round(1E3*
a);d!==k&&c.postEvent(x.SEEK,{offsetBefore:d,offsetAfter:k,heatmapDisplayed:!1,spectrumType:"",spectrumColor:0,relatedConcepts:""})}w=a});a(b)});break;case "link":c.postStartSessionEvent();D(d,r,u,c,function(d,k){var b=k.mediaList[0],f=document.createElement("TABLE");f.style="border-style:none";var r=f.appendChild(document.createElement("TR")).appendChild(document.createElement("TD")).appendChild(document.createElement("A"));r.href="#";r.appendChild(document.createElement("IMG")).src=encodeURI(b.thumbnailImageUrl);
var g=f.appendChild(document.createElement("TR")).appendChild(document.createElement("TD"));g.style="text-align:center";g=g.appendChild(document.createElement("A"));g.href="#";g.appendChild(document.createTextNode("Click to play"));var w=function(){c.postPlayStateEvent(x.PLAY,0,function(){window.location=b.mobileUrls[0].mobileUrl});return!1};r.onclick=w;g.onclick=w;a(f)});break;case "install-flash":j.Flash.canUpgrade?(k=!0===j.Flash.isActiveX?"ActiveX":"PlugIn",document.title=document.title.slice(0,
47)+" - Flash Player Installation",y(a,"http://assets.delvenetworks.com/player/playerProductInstall.swf","MMredirectURL="+window.location+"&MMplayerType="+k+"&MMdoctitle="+document.title,g,f,w,b)):a('<table width="'+g+'" height="'+f+'" bgcolor="black" style="background-color:black; margin-left:auto; margin-right:auto"><tr><td align="center" style="text-align:center; vertical-align:middle"><a href="http://www.adobe.com/go/getflash/" style="text-decoration:underline; color:white"><span style="font-size:12px; color:white">You need to have the latest version of Adobe Flash Player to view this content.<br/>Please click here to continue.</span></a></td></tr></table>')}return null}
function y(a,d,k,b,g,f,w){var c="",e;if("string"===typeof k)c=k;else if("object"===typeof k)for(e in k)c+=encodeURIComponent(e)+"="+encodeURIComponent(k[e])+"&";a('<object type="application/x-shockwave-flash" id="'+f+'" name="'+f+'" width="'+b+'" height="'+g+'" data="'+d+'"><param name="movie" value="'+d+'"/><param name="wmode" value="'+w+'"/><param name="allowScriptAccess" value="always"/><param name="allowFullScreen" value="true"/><param name="flashVars" value="'+c+'"/></object>');return document.getElementById(f)}
function D(a,d,k,b,g){var f;d.mediaId?f=a.playlistService+"/media/"+d.mediaId+"/getMobilePlaylistByMediaId?platform="+k:d.channelId?f=a.playlistService+"/channel/"+d.channelId+"/getFirstAvailableMobilePlaylistByChannelId?platform="+k:d.channelListId&&(f=a.playlistService+"/channel_list/"+d.channelListId+"/getFirstAvailableMobilePlaylistByChannelListId?platform="+k);O(f,function(a){a&&a.mediaList&&a.mediaList[0]?(a.id&&b.setChannelId(a.id),a.mediaList[0].mediaId&&b.setMediaId(a.mediaList[0].mediaId),
0<a.mediaList[0].mobileUrls.length?g(k,a):showError("Video Not Available For This Device")):showError("Video Not Available")})}function C(a){function d(a){return("object"===typeof a||"function"===typeof a)&&a.nodeType}if("undefined"===typeof a)return function(a){d(a)?document.body.appendChild(a):document.write(a)};"string"===typeof a&&(a=document.getElementById(a));if(d(a)){if("OBJECT"===a.nodeName){var b=a.parentNode,c=a.nextSibling,g=!1;return function(f){var e=document.createElement("DIV");d(f)?
e.appendChild(f):e.innerHTML=f;g||(b.replaceChild(e.firstChild,a),g=!0);for(;e.firstChild;)b.insertBefore(e.firstChild,c)}}return function(b){d(b)?a.appendChild(b):a.innerHTML+=b}}return null}var l="http://production.ps.delve.cust.lldns.net/r/PlaylistService",z="http://mcs.delve.cust.lldns.net/r/MetricsCollectionService",J="http://cps.lvp.llnw.net/r/CuePointService",v="//videoplatform.limelight.com/player/html-player.js",c="//assets.delvenetworks.com/player/resources/iframe.html",u="Mobile3gp",e=
navigator,j,b=e.userAgent.toLowerCase(),p=e.platform.toLowerCase(),n=/msie/.test(b),m=/msie\s\d\d/.test(b),h=/linux/.test(p?p:b),p=/android \d+\x2E\d+/.test(b),K=/android [2-9]+\x2E\d+/.test(b),W=/ipad/.test(b),E=/iphone|ipad|ipod/.test(b),q=/silk/.test(b),L=/blackberry/.test(b),A=/symbian|series60/.test(b),P=/opera mobi|opera tablet/.test(b),I=/fennec/.test(b);/playbook/.test(b);var X=/mobile/.test(b)||p,L=p||E||q||L||A||P||I||X,A=[0,0,0];if(E&&(b=b.match(/os (.*) like mac os x/))&&1<b.length){var A=
[],b=b[1].split("_"),s;for(s in b)A.push(parseInt(b[s]));for(;3>A.length;)A.push(0)}s=document.createElement("VIDEO");s=!s.canPlayType?"":s.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"');var K=(K||q||E)&&!I,q=document.createElement("VIDEO"),q=!q.canPlayType?"":q.canPlayType("application/vnd.apple.mpegurl"),I="probably"===q||E?"HttpLiveStreaming":"MobileH264",F=function(){var a=null;if("undefined"!==typeof e.plugins&&"object"==typeof e.plugins["Shockwave Flash"]){if((a=e.plugins["Shockwave Flash"].description)&&
!("undefined"!==typeof e.mimeTypes&&e.mimeTypes["application/x-shockwave-flash"]&&!e.mimeTypes["application/x-shockwave-flash"].enabledPlugin))return a=a.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),[parseInt(a.replace(/^(.*)\..*$/,"$1"),10),parseInt(a.replace(/^.*\.(.*)\s.*$/,"$1"),10),/[a-zA-Z]/.test(a)?parseInt(a.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0]}else if("undefined"!==typeof window.ActiveXObject)try{var d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(d&&(a=d.GetVariable("$version")))return a=
a.split(" ")[1].split(","),[parseInt(a[0],10),parseInt(a[1],10),parseInt(a[2],10)]}catch(b){}return[0,0,0]}(),b=function(a,d,b){return F[0]>a||F[0]==a&&(F[1]>d||F[1]==d&&F[2]>=b)},n={canUpgrade:!h&&b(6,0,65),H264:b(9,0,115),hasAdaptiveStreaming:b(10,0,0),isActiveX:n},p=n.H264&&!p?"flash":L?"probably"===s||K?!P&&(!E||W||!(5>A[0]))?"html":"video":"link":"install-flash";"install-flash"===p&&(m&&"assets.delvenetworks.com"!==window.location.host)&&(p="iframe");j={Metrics:{H264:s,HLS:q},embedMode:p,htmlCodec:I,
Flash:n,loadingProtocol:"https:"===document.location.protocol?"https:":"http:"};var N,G=[];N=function(a,b){if(void 0!==LimelightPlayerUtil.Player)b(LimelightPlayerUtil.Player);else if(G.push(b),void 0===LimelightPlayerUtil.playerLoadedCallback){var k=document.getElementsByTagName("head")[0]||document.documentElement,c=document.createElement("SCRIPT");c.type="text/javascript";c.src=a.htmlPlayerLocation;c.charset="utf-8";LimelightPlayerUtil.playerLoadedCallback=function(a){LimelightPlayerUtil.Player=
a;delete LimelightPlayerUtil.playerLoadedCallback;k&&k.removeChild(c);G.forEach(function(b){b(a)});G=[]};c.onerror=function(){G.forEach(function(a){a(null)});G=[]};k.insertBefore(c,k.firstChild)}};var M,Q=[];M=function(a,b,k,c,g,f,e){function j(a){var b={},d;for(d in a)b[d]="object"===typeof a[d]&&a[d]?j(a[d]):a[d];return b}var h=document.createElement("IFRAME");h.id=b;h.width=k;h.height=c;h.src=a.playerIframeLocation;h.style.border="none";e(h);var l=document.getElementById(b).contentWindow,m={},
n={},p={},u=0,v={},x=0,t=1,q=null,s=null,y=void 0;window.addEventListener("message",function(b){var d,c=b.data.state;c&&(c.channelList&&(m=c.channelList),c.channel&&(n=c.channel),c.media&&(p=c.media),c.index&&(u=c.index),c.playState&&(v=c.playState),c.position&&(x=c.position),c.volume&&(t=c.volume),c.quality&&(q=c.quality),c.actualQuality&&(s=c.actualQuality),c.customEvents&&(y=c.customEvents));switch(b.data.type){case "event":"function"===typeof delvePlayerCallback&&delvePlayerCallback(b.data.id,
b.data.eventName,b.data.data);break;case "init":l.postMessage({type:"init",embed:"../embed.js",flashVars:g,resourceLocations:a},"*");break;case "api":d={};for(var k in b.data.funcs){var c=b.data.funcs[k],f=function(a){return function(){l.postMessage({type:"func",name:a,args:Array.prototype.slice.call(arguments)},"*")}}(c);d[c]=f}d.registerPlayer=function(){};d.getPlayers=function(){return Q};d.doGetActualQuality=function(){return!s?null:s.name};d.doGetQuality=function(){return!q?null:q.name};d.doGetQualityDetails=
function(){return j({actual:s,selected:q})};d.doGetCurrentIndex=function(){return u};d.doGetCurrentMedia=function(){return j(p)};d.doGetCurrentChannel=function(){return j(n)};d.doGetCurrentChannelList=function(){return j(m)};d.doGetCurrentPlayState=function(){return j(v)};d.doGetCustomEvents=function(){return j(y)};d.doGetPlayheadPositionInMilliseconds=function(){return x};var e=d.doSetVolume;d.doSetVolume=function(a){a||(a=0);if("number"===typeof a)return 0>a&&(a=0),1<a&&(a=1),t=a,e(a)};d.doGetVolume=
function(){return t};delete d.doGetChannels;delete d.doGetChannelMedia;d.getPlayer=function(){return d};d.getPlayerNodeByIdOrName=function(a){var d=document.getElementById(a);return d&&d.doPlay?d:(a=document.getElementsByName(a))&&null!=a.length?a[0]:null};DelvePlayer=d;for(var r in d)h[r]=d[r];Q.push(d)}})};var x,R=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var d=16*Math.random()|0;return("x"==a?d:d&3|8).toString(16)}).toUpperCase()},Y=R(),S={H264:j.Metrics.H264,
HLS:j.Metrics.HLS},Z=e.userAgent,$=e.platform,T,H;n=document.cookie.indexOf("Limelight_Embed_Code_UserId=");m=n+27+1;!n&&"Limelight_Embed_Code_UserId"!=document.cookie.substring(0,27)||-1==n?H=null:(n=document.cookie.indexOf(";",m),-1==n&&(n=document.cookie.length),H=unescape(document.cookie.substring(m,n)));T=function(){if(!H){var a=H=R(),d=365,b=new Date;b.setTime(b.getTime());d&&(d*=864E5);b=new Date(b.getTime()+d);document.cookie="Limelight_Embed_Code_UserId="+escape(a)+(d?";expires="+b.toGMTString():
"")+""}return H};var U,aa=+new Date;U=function(){return new Date-aa};var V,ba=0;V=function(a,d,b){var c="_limelight_embed_ajax_"+ba++,g=document.createElement("IFRAME");g.id=c;g.name=c;g.style.cssText="display:none;width:0px;height:0px;";(document.getElementsByTagName("body")[0]||document.documentElement).appendChild(g);var f=document.createElement("FORM");f.setAttribute("target",c);f.setAttribute("method","POST");f.setAttribute("action",a);for(field in d)a=document.createElement("INPUT"),a.setAttribute("type",
"hidden"),a.setAttribute("name",field),a.setAttribute("value",JSON.stringify(d[field])),f.appendChild(a);g.appendChild(f);g.onload=function(){void 0!==b&&b();setTimeout(function(){g.parentNode.removeChild(g)},0)};f.submit()};x={HEARTBEAT:"Heartbeat",MEDIA_COMPLETE:"MediaComplete",PLAY:"Play",PAUSE:"Pause",SEEK:"Seek",START_SESSION:"StartSession",create:function(a,d,b){var c={},g=null;S.embedMode=b;var f={postEvent:function(b,k,f){var g={channelListId:c.channelListId||d.channelListId,channelId:c.channelId||
d.channelId,mediaId:c.mediaId||d.mediaId,millisecondsElapsed:U()},e;for(e in g)void 0===g[e]&&(g[e]="");for(e in k)g[e]=void 0===k[e]?"":k[e];V(a+"/recordMetricsEvent",{sourceInstanceId:Y,source:"Limelight Embed Code",sourceVersion:1,eventType:b,data:g},f)},postStartSessionEvent:function(){this.postEvent(x.START_SESSION,{adConfigurationChannelId:d.adConfigurationChannelId,htmlCapabilities:JSON.stringify(S),pageURL:window.location.href,platform:$,playerProviderId:"Delve Networks",userAgent:Z,userId:T(),
version:"1.5.2"})},postPlayStateEvent:function(a,b,d){var c;if(void 0===d)c=void 0;else{var e=!1;c=function(){e||(e=!0,d.apply(this,arguments))}}this.postEvent(a,{positionInMilliseconds:b},c);void 0!==d&&setTimeout(c,1E3)},setChannelListId:function(a){c.channelListId=a},setChannelId:function(a){c.channelId=a},setMediaId:function(a){c.mediaId=a},startHeartbeat:function(a){null!==g&&clearInterval(g);g=setInterval(function(){a.isPlaying()&&f.postEvent(x.HEARTBEAT,{droppedFrames:0,droppedFramesRatio:"",
selectedMediaQuality:a.quality,positionInMilliseconds:a.getPosition(),maxBytesPerSecond:"",currentBitrate:""})},3E4)},stopHeartbeat:function(){null!==g&&clearInterval(g);g=null}};return f}};var O,ca=0;O=function(a,d){var b="_"+ca++;a+="&jsonp=LimelightPlayerUtil.jsonpCallback."+b;var c=document.getElementsByTagName("head")[0]||document.documentElement,e=document.createElement("SCRIPT");e.type="text/javascript";e.src=a;e.charset="utf-8";LimelightPlayerUtil.jsonpCallback[b]=function(a){delete LimelightPlayerUtil.jsonpCallback[b];
d(a);c&&c.removeChild(e)};e.onerror=function(){d(null)};c.insertBefore(e,c.firstChild)};return{jsonpCallback:[],initEmbed:function(a,b){b=b||{};var c=document.getElementById(a);if(null===c)return console&&(console.error&&"function"===typeof console.error)&&console.error("No such element: "+a),null;var e=c.width,g=c.height,f=c.firstChild;b.id=a;for(var h="",l={};null!==f;){if("PARAM"===f.nodeName)switch(f.name){case "flashVars":for(var h=f.value,l={},m=h.split("&"),n=0;n<m.length;n++){var p=m[n],q=
p.indexOf("=");-1===q?l[decodeURIComponent(p)]="true":l[decodeURIComponent(p.substring(0,q))]=decodeURIComponent(p.substring(q+1))}break;case "wmode":b.wmode=f.value}f=f.nextSibling}b=t(b);f=b.embedMode||j.embedMode;return"flash"!==f?(c=C(c),B(c,b.resources,h,l,e,g,b.id,b.wmode,f)):c},embedPlayer:function(a,b,c,e,g){g=C(g);e=t(e);var f=e.embedMode||j.embedMode;return"flash"===f?y(g,j.loadingProtocol+(j.Flash.hasAdaptiveStreaming?"//assets.delvenetworks.com/player/fp10loader.swf":"//assets.delvenetworks.com/player/fp9loader.swf"),
a,b,c,e.id,e.wmode):B(g,e.resources,null,a,b,c,e.id,e.wmode,f)}}}());
