title:            TFC Blog
tagline:          The Trading and Finance Blog for TFC
description:      Updates & Prior Meeting Recaps. Occasionaly some commentary, and always something new.
#Comment out url when working locally to resolve base urls correctly
url: http://jekyll.gtat.me

# Owner/author information
owner:
  name:           Luke Aslanian
  avatar:         avatar.png
  bio:            "Trader & TFC Founder"
  email:          phstfc@gmail.com
  twitter:        phstfc        
  github:         tfclub       
  instagram:      --    
  dribbble:       --
  disqus:         phstfc
  # Plug in your disqus shortname!
  

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/tfclub/TFC-Blog
    external: true
  - title: TFC Website
    url: http://phstfc.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Phoenix
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
